In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a.shape

(3,)

In [31]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.random.seed(30)
np.random.rand(3,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ],
       [0.58569427, 0.4066901 , 0.13623432, 0.54413629]])

In [10]:
np.eye(4) #Matrice identité

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [14]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [32]:
print(b)
print('\n')
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
d = np.hstack((b,c))
d

array([[0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.]])

In [33]:
e = np.vstack((b,c))
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
b.size

9

In [35]:
e.size

18

In [36]:
f = e.reshape((2,9))
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## PART 2

In [3]:
import numpy as np
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
A[:,0]

array([1, 4, 7])

In [5]:
A[0,:]

array([1, 2, 3])

In [7]:
A[0]

array([1, 2, 3])

In [10]:
A[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [15]:
B = A
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
B[0:2, 0:2] = 10
B

array([[10, 10,  3],
       [10, 10,  6],
       [ 7,  8,  9]])

In [29]:
C = B
C[0:3,0:3] = 10
C

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [31]:
C[:,-2:] =1
C

array([[10,  1,  1],
       [10,  1,  1],
       [10,  1,  1]])

In [34]:
D = np.zeros((4,4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
D[1:3,1:3] = 1
D

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [42]:
E = np.zeros((5,5))
E[::2,::2] = 1
E

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

In [56]:
F = np.random.randint(0,10,[5,5])
F

array([[5, 9, 2, 9, 3],
       [2, 8, 0, 2, 6],
       [1, 5, 3, 5, 0],
       [9, 3, 1, 1, 2],
       [3, 5, 4, 9, 0]])

In [53]:
F > 5

array([[ True,  True,  True, False,  True],
       [ True, False, False,  True, False],
       [False,  True, False, False, False],
       [ True, False, False,  True, False],
       [ True, False,  True, False,  True]])

In [59]:
F[(F<5) | (F>8)] = 10
F

array([[ 5, 10, 10, 10, 10],
       [10,  8, 10, 10,  6],
       [10,  5, 10,  5, 10],
       [10, 10, 10, 10, 10],
       [10,  5, 10, 10, 10]])

## Part 3 : Mathematiques & Statistiques

### Math

In [1]:

import numpy as np

In [3]:
np.random.seed(0)
A = np.random.randint(0,10,[2,3])
A

array([[5, 0, 3],
       [3, 7, 9]])

In [4]:
A.sum()

27

In [5]:
A.sum(axis=0)

array([ 8,  7, 12])

In [6]:
A.sum(axis=1)

array([ 8, 19])

In [7]:
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [8]:
A.argsort() #retourne les index dans l'ordre de tri du tableau ( sans modifier le tableau )

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [9]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

### Stats

In [10]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [20]:
A.mean(axis=0)

array([4. , 3.5, 6. ])

In [16]:
np.corrcoef(A)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [15]:
np.corrcoef(A)[0,1]

-0.563621480190678

In [26]:
values, counts = np.unique(A, return_counts=True)
values

array([0, 3, 5, 7, 9])

In [27]:
counts

array([1, 2, 1, 1, 1], dtype=int64)

In [28]:
counts.argsort()

array([0, 2, 3, 4, 1], dtype=int64)

### Naan corrections

In [33]:
B = np.random.randn(5,5)
B[0, 2] = np.nan
B[4,3] = np.nan
B

array([[-1.49874039, -1.23063497,         nan, -0.99838235, -0.3676376 ],
       [ 1.73719932,  0.59361275, -0.54236358, -1.71967238, -0.57890879],
       [ 1.42694855,  0.27699691,  0.78966713,  0.32207411,  0.70039238],
       [ 0.38871663, -0.04126386,  0.29588432, -0.42527999,  1.72763912],
       [-0.86835257, -0.82097758, -1.09974201,         nan,  0.45628701]])

In [34]:
np.nanmean(B) #permet de calculer la moyenne en ignorant les nan

-0.06419729740993241

In [38]:
np.isnan(B).sum()/B.size

0.08

In [40]:
B[np.isnan(B)] = 0
B

array([[-1.49874039, -1.23063497,  0.        , -0.99838235, -0.3676376 ],
       [ 1.73719932,  0.59361275, -0.54236358, -1.71967238, -0.57890879],
       [ 1.42694855,  0.27699691,  0.78966713,  0.32207411,  0.70039238],
       [ 0.38871663, -0.04126386,  0.29588432, -0.42527999,  1.72763912],
       [-0.86835257, -0.82097758, -1.09974201,  0.        ,  0.45628701]])

## Algèbre linéaire

In [44]:
A = np.ones((2 , 3))
B = np.ones((3 , 2))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
A.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [47]:
A.dot(B) #Produit matriciel

array([[3., 3.],
       [3., 3.]])

In [48]:
B.dot(A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [50]:
C = np.random.randint(0,10,[3,3])
C

array([[6, 5, 7],
       [8, 8, 9],
       [2, 8, 6]])

In [51]:
np.linalg.det(C) #Determinant

41.999999999999986

In [52]:
np.linalg.inv(C) #inverse de la matrice

array([[-0.57142857,  0.61904762, -0.26190476],
       [-0.71428571,  0.52380952,  0.04761905],
       [ 1.14285714, -0.9047619 ,  0.19047619]])